# Customization for Harley-Davidson bikes
subMenu = std_separator
subMenu = cfcDialog,    "Cooling Fan Control"
subMenu = cpcDialog,    "Cooling Pump Control"
subMenu = ccfcDialog,   "Chassis Cooling Fan Control"
subMenu = prgselDialog, "Purge Solenoid Control"

subMenu = ridingModeLiveDialog,	  "Riding Modes Live"
subMenu = engineBrakingDialog,    "Engine Braking"
subMenu = vmaxLimiterDialog,      "Vmax Limiter"
