	dialog = veFrontTableDialog
		topicHelp = "veTableDialogHelp"
		panel = veFrontTableTbl, South

	dialog = instantAccelFuelDialog, "Instant Accel Fuel"
		field = "Instant Accel Window (ms)", instantAccelShotWindowMs
		field = "Instant Accel Min Spacing (ms)", instantAccelShotTopupMinSpacingMs
		field = "Instant Accel Min Increment (ms)", instantAccelShotTopupMinIncrementMs
		field = "Instant Accel Min dTPS (%)", instantAccelShotMinDeltaTps
		panel = instantAccelShotTableTbl, West
		panel = instantAccelShotCltCorrCurve, East

	dialog = engineBrakingDialog, "Engine Braking"
		field = "ETB Offset Mode 1 (%)", engineBrakingEtbOffsetMode1
		field = "ETB Offset Mode 2 (%)", engineBrakingEtbOffsetMode2
		field = "ETB Offset Mode 3 (%)", engineBrakingEtbOffsetMode3
		field = "ETB Offset Mode 4 (%)", engineBrakingEtbOffsetMode4
		field = "ETB Offset Mode 5 (%)", engineBrakingEtbOffsetMode5
		field = "Engage RPM (min)", engineBrakingRpmEngage
		field = "Full Effect RPM", engineBrakingRpmFull
		field = "Min Vehicle Speed (kph)", engineBrakingMinVss
		field = "Max Base ETB Target (%)", engineBrakingMaxBaseEtbTarget

	dialog = etbTargetSlewDialog, "ETB Target Slew"
		panel = etbTargetSlewUpRateCurve, South

	indicatorPanel = ridingModeIndicatorsPanel, 2
		indicator = { luaGauges1 == 12 }, "RAIN", "RAIN", white, black, green, black
		indicator = { luaGauges1 == 1 }, "ROAD", "ROAD", white, black, green, black
		indicator = { luaGauges1 == 3 }, "SPORT", "SPORT", white, black, green, black
		indicator = { luaGauges1 == 4 }, "TRACK", "TRACK", white, black, green, black
		indicator = { luaGauges1 == 7 }, "TRACK+", "TRACK+", white, black, green, black
		indicator = { luaGauges1 == 8 }, "USER A", "USER A", white, black, green, black
		indicator = { luaGauges1 == 9 }, "USER B", "USER B", white, black, green, black

	dialog = ridingModeLiveDialog, "Riding Modes Live"
		gauge = ridingModeActiveGauge
		gauge = ridingModeRequestedGauge
		gauge = ridingModeEngineMapGauge
		gauge = ridingModeEngineBrakeGauge
		gauge = ridingModeThrottleRespGauge
		panel = ridingModeIndicatorsPanel

	dialog = cfcDialog, "Coolant Fan Control"
		field = "On Temperature", cfcOnTemperature
		field = "Off Temperature", cfcOffTemperature
		field = "Disable when engine stopped", cfcDisableWhenEngineStopped
		field = "Disable above vehicle speed", cfcDisableAboveSpeed
		#field = "Idle Adder", cfcIdleAdder
		commandButton = "Test CFC On", cmd_cfc_force_on
		commandButton = "Test CFC Off", cmd_cfc_auto
		