	dialog = veFrontTableDialog
		topicHelp = "veTableDialogHelp"
		panel = veFrontTableTbl, South

	dialog = instantAccelFuelDialog, "Instant Accel Fuel"
		field = "Instant Accel Window (ms)", instantAccelShotWindowMs
		field = "Instant Accel Min Spacing (ms)", instantAccelShotTopupMinSpacingMs
		field = "Instant Accel Min Increment (ms)", instantAccelShotTopupMinIncrementMs
		field = "Instant Accel Min dTPS (%)", instantAccelShotMinDeltaTps
		panel = instantAccelShotTableTbl, West
		panel = instantAccelShotCltCorrCurve, East

	dialog = engineBrakingDialog, "Engine Braking"
		field = "ETB Offset Mode 1 (%)", engineBrakingEtbOffsetMode1
		field = "ETB Offset Mode 2 (%)", engineBrakingEtbOffsetMode2
		field = "ETB Offset Mode 3 (%)", engineBrakingEtbOffsetMode3
		field = "ETB Offset Mode 4 (%)", engineBrakingEtbOffsetMode4
		field = "ETB Offset Mode 5 (%)", engineBrakingEtbOffsetMode5
		field = "Engage RPM (min)", engineBrakingRpmEngage
		field = "Full Effect RPM", engineBrakingRpmFull
		field = "Min Vehicle Speed (kph)", engineBrakingMinVss
		field = "Max Base ETB Target (%)", engineBrakingMaxBaseEtbTarget

	dialog = etbTargetSlewDialog, "ETB Target Slew"
		panel = etbTargetSlewUpRateCurve, South

	indicatorPanel = ridingModeIndicatorsPanel, 2
		indicator = { luaGauges1 == 12 }, "RAIN", "RAIN", white, black, green, black
		indicator = { luaGauges1 == 1 }, "ROAD", "ROAD", white, black, green, black
		indicator = { luaGauges1 == 3 }, "SPORT", "SPORT", white, black, green, black
		indicator = { luaGauges1 == 4 }, "TRACK", "TRACK", white, black, green, black
		indicator = { luaGauges1 == 7 }, "TRACK+", "TRACK+", white, black, green, black
		indicator = { luaGauges1 == 8 }, "USER A", "USER A", white, black, green, black
		indicator = { luaGauges1 == 9 }, "USER B", "USER B", white, black, green, black

	dialog = ridingModeLiveDialog, "Riding Modes Live"
		gauge = ridingModeActiveGauge
		gauge = ridingModeRequestedGauge
		gauge = ridingModeEngineMapGauge
		gauge = ridingModeEngineBrakeGauge
		gauge = ridingModeThrottleRespGauge
		panel = ridingModeIndicatorsPanel

	dialog = cfcSubDialog
		field = "Output", cfcOutputPin
		field = "Upper Speed Threshold", cfcHighSpeedThreshold
		field = "Lower Speed Threshold", cfcLowSpeedThreshold
		field = "Lower Speed On Temperature", cfcLowSpeedOnTemp
		field = "Lower Speed Off Temperature", cfcLowSpeedOffTemp
		field = "Higher Speed On Temperature", cfcHighSpeedOnTemp
		field = "Higher Speed Off Temperature", cfcHighSpeedOffTemp
		field = "Disable when engine stopped", cfcDisableWhenEngineStopped
		field = "Maximum runtime after engine shutdown", cfcMaxRuntimeAfterEngShutdown
		field = "Engine Shutdown Off Temperature", cfcEngShutdownOffTemp
		;field = "Idle Adder", cfcIdleAdder

	dialog = cfcTestButtons, "", xAxis
		commandButton = "Test CFC Force On", cmd_cfc_force_on
		commandButton = "Test CFC Auto", cmd_cfc_auto

	indicatorPanel = cfcIndicatorPanel, 1
		indicator = { luaGauges8 == 2 || luaGauges8 == 3 || luaGauges8 == 6 || luaGauges8 == 7 || luaGauges8 == 10 || luaGauges8 == 11 || luaGauges8 == 14 || luaGauges8 == 15 }, "CFC off", "CFC on", white, black, green, black

	dialog = cfcDialog, "Coolant Fan Control"
		panel = cfcSubDialog
		panel = cfcTestButtons
		panel = cfcIndicatorPanel

	dialog = ccfcSubDialog
		;field = "Output", ccfcOutputPin
		field = "Enable below vehicle speed", ccfcEnableBelowSpeed
		field = "Disable above vehicle speed", ccfcDisableAboveSpeed
		field = "High ambient temperature threshold", ccfcHighAmbTempThreshold
		field = "Low ambient temperature threshold", ccfcLowAmbTempThreshold
		field = "Lower Amb. Temp.: Disable below engine temperature", ccfcLowAmbDisableBelowEngTemp
		field = "Lower Amb. Temp.: Enable above engine temperature", ccfcLowAmbEnableAboveEngTemp
		field = "Higher Amb. Temp.: Disable below engine temperature", ccfcHighAmbDisableBelowEngTemp
		field = "Higher Amb. Temp.: Enable above engine temperature", ccfcHighAmbEnableAboveEngTemp
		;field = "Idle Adder", ccfcIdleAdder

	dialog = ccfcTestButtons, "", xAxis
		commandButton = "Test CCFC Force On", cmd_ccfc_force_on
		commandButton = "Test CCFC Force Auto", cmd_ccfc_auto

	indicatorPanel = ccfcIndicatorPanel, 2
		indicator = { luaGauges7 == 0 }, "CCFC enabled",  "CCFC disabled", green, black, red, black
		indicator = { luaGauges8 == 4 || luaGauges8 == 5 || luaGauges8 == 6 || luaGauges8 == 7 || luaGauges8 == 12 || luaGauges8 == 13 || luaGauges8 == 14 || luaGauges8 == 15 }, "Fan off",      "Fan on",        white, black, green,  black
		indicator = { luaGauges7 == 1 }, "Mode: OFF",      "Mode: OFF",     white, black, red,    black
		indicator = { luaGauges7 == 2 }, "Mode: AUTO",      "Mode: AUTO",    white, black, green,  black
		indicator = { luaGauges7 == 3 }, "Mode: ON",      "Mode: ON",      white, black, green,  black

	dialog = ccfcDialog, "Chassis Cooling Fan Control"
		panel = ccfcSubDialog
		panel = ccfcTestButtons
		panel = ccfcIndicatorPanel

	dialog = prgselSubDialog
		;field = "Output", prgselOutputPin
		field = "Purge Solenoid Active", prgselActive
		field = "Activate above RPM", prgselRPM
		field = "Activate above Velocity", prgselSpeed
		field = "Activate above TGS", prgselLowerTGS
		field = "Activate below TGS", prgselUpperTGS
		field = "Activate above Coolant Temperature", prgselCltTemp
		field = "Activate after running engine time", prgselActAfterTime
		field = "Purge Solenoid PWM Frequency", prgselPWMFreq
		field = "Purge Solenoid PWM Duty Cycle", prgselPWMDuty

	dialog = prgselTestButtons, "", xAxis
		commandButton = "Test PRGSEL Force On", cmd_prgsel_force_on
		commandButton = "Test PRGSEL Auto", cmd_prgsel_auto

	indicatorPanel = prgselIndicatorPanel, 1
		indicator = { luaGauges8 == 1 || luaGauges8 == 3 || luaGauges8 == 5 || luaGauges8 == 7 || luaGauges8 == 9 || luaGauges8 == 11 || luaGauges8 == 13 || luaGauges8 == 15 }, "PRGSEL off", "PRGSEL on", white, black, green, black

	dialog = prgselDialog, "Purge Valve Solenoid"
		panel = prgselSubDialog
		panel = prgselTestButtons
		panel = prgselIndicatorPanel

	dialog = cpcSubDialog
		;field = "Output", cpcOutputPin
		field = "Lower On Temperature", cpcOnTemp
		field = "Lower Off Temperature", cpcOffTemp
		field = "Disable when engine stopped", cpcDisableWhenEngineStopped
		;field = "Idle Adder", cpcIdleAdder

	dialog = cpcTestButtons, "", xAxis
		commandButton = "Test CPC Force On", cmd_cpc_force_on
		commandButton = "Test CPC Auto", cmd_cpc_auto

	indicatorPanel = cpcIndicatorPanel, 1
		indicator = { luaGauges8 >= 8 }, "CPC off", "CPC on", white, black, green, black

	dialog = cpcDialog, "Coolant Pump Control"
		panel = cpcSubDialog
		panel = cpcTestButtons
		panel = cpcIndicatorPanel
		