# Customization for Harley-Davidson bikes
subMenu = std_separator
subMenu = cfcDialog,    "Cooling Fan Control"
subMenu = cpcDialog,    "Cooling Pump Control"
subMenu = ccfcDialog,   "Chassis Cooling Fan Control"
subMenu = prgselDialog, "Purge Solenoid Control"

subMenu = ridingModeLiveDialog,	  "Riding Modes Live"
subMenu = engineBrakingDialog,    "Engine Braking"
subMenu = vmaxLimiterDialog,      "Vmax Limiter"

groupMenu = "Autotuning"
	groupChildMenu = autotuneGeneralDialog, "General configuration"
	groupChildMenu = autotuneConditionsDialog, "Autotune Conditions"
	groupChildMenu = lambdaDelayTableDialog, "Lambda Delay"
	groupChildMenu = autotuneVerySlowDialog, "Learning Rate: Very Slow Parameters"
	groupChildMenu = autotuneSlowDialog, "Learning Rate: Slow Parameters"
	groupChildMenu = autotuneNormalDialog, "Learning Rate: Normal Parameters"
	groupChildMenu = autotuneFastDialog, "Learning Rate: Fast Parameters"
	groupChildMenu = autotuneVeryFastDialog, "Learning Rate: Very Fast Parameters"
